name: Backend Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run tests
        run: |
          cd backend
          npm run test
